/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxfuncs.h
 *  model: PositionControllerTilt
 *  expmt: Jiwy
 *  date:  June 2, 2021
 *  time:  12:30:24 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

#ifndef XX_FUNCS_H
#define XX_FUNCS_H

/* Our own include files */
#include "xxtypes.h"

/* Global constants */
extern XXBoolean xx_initialize;
extern XXBoolean xx_major;
extern XXBoolean xx_stop_simulation;

/* Wrapper functions around strings */
XXDouble XXString2Double(const char* argument);
const char* XXDouble2String(XXDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

