/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmain.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 2, 2021
 *  time:  12:30:12 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file is a demo application of how the submodel function can 
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO ! 
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY 
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

/* 20-sim include files */
#include "xxsubmod.h"
#include "stdio.h"
#include <time.h>

/* The main function */
int main()
{
	int looptime = 100000000;
	long ctr = 0;
	long ctr_1 = 0;
	XXDouble u [2 + 1];
	XXDouble y [2 + 1];

	/* Initialize the inputs and outputs with correct initial values */
	u[0] = 2.0;		/* in */
	u[1] = 0.0;		/* position */

	y[0] = 0.0;		/* corr */
	y[1] = 0.0;		/* out */


	/* Initialize the submodel itself */
	XXInitializeSubmodel (u, y, xx_time);

	/* Simple loop, the time is incremented by the integration method */
	//while ( (xx_time < xx_finish_time) && (xx_stop_simulation == XXFALSE) )
	clock_t t = clock();
	while (1)
	{
		/* Call the submodel to calculate the output */
		
		if (ctr - ctr_1 > looptime) {
			
			if (u[1] < 2) u[1] = u[1] += 0.1;
			float out = y[1];
			float pos = u[1];
			printf("Position = %f, pwm sig = %f \n", pos, out);
			XXCalculateSubmodel(u, y, xx_time);
			ctr_1 = ctr;
			printf("waiting took %d ticks \n", (clock()-t));
			t = clock();
		}
		
		ctr++;
		if (ctr < 0) return 0;
	}

	/* Perform the final calculations */
	XXTerminateSubmodel (u, y, xx_time);

	/* and we are done */
	return 0;
}

